### ISSUE TITLE
./gradlew publishEventuateArtifacts Works on 5.1.1 but fails on 6.3

### ISSUE THREAD

**Issue by cer** [eventuate-foundation/eventuate-plugins-gradle#3]
```
Caused by: java.lang.ClassCastException: org.gradle.StartParameter cannot be cast to org.gradle.api.internal.StartParameterInternal
        at org.gradle.initialization.layout.BuildLayoutConfiguration.<init>(BuildLayoutConfiguration.java:37)
        at org.gradle.internal.service.scopes.BuildScopeServices.createBuildLayout(BuildScopeServices.java:217)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
```

**Comment by cer** [comment]
Works on 6.8.3
